name: CD

on:
  workflow_run:
    workflows: ['CI']
    branches: [master]
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build
        env:
          REACT_APP_GITHUB_SHA: ${{ github.sha }}

      - name: Deploy to Odin
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ODIN_GIT_GH_PEM }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: 'build/'
          REMOTE_HOST: ${{ secrets.ODIN_HOST }}
          REMOTE_USER: git
          TARGET: /var/www/iledopapiezowej/build

      - name: Purge cf cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CF_ZONE_ILEDOPAPIEZOWEJ }}
          CLOUDFLARE_TOKEN: ${{ secrets.CF_TOKEN_PURGE }}
